//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string Login1 { get; set; }
        public Nullable<int> IDNumber { get; set; }
        public string FIO { get; set; }
        public int ID { get; set; }
    }
}
