//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasker
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTask
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public Nullable<int> Position { get; set; }
        public string Item { get; set; }
        public string ItemBatch { get; set; }
        public string ItemBeginSerial { get; set; }
        public Nullable<int> ItemAmount1 { get; set; }
        public Nullable<int> ItemLength1 { get; set; }
        public Nullable<int> ItemAmount2 { get; set; }
        public Nullable<int> ItemLength2 { get; set; }
        public Nullable<int> ItemAmount3 { get; set; }
        public Nullable<int> ItemLenth3 { get; set; }
        public Nullable<int> ItemAmount4 { get; set; }
        public Nullable<int> ItemLength4 { get; set; }
        public Nullable<int> ItemAmount5 { get; set; }
        public Nullable<int> ItemLength5 { get; set; }
        public Nullable<int> ItemAmount6 { get; set; }
        public Nullable<int> ItemLength6 { get; set; }
        public Nullable<int> ItemAmount7 { get; set; }
        public Nullable<int> ItemLength7 { get; set; }
        public Nullable<int> ItemAmount8 { get; set; }
        public Nullable<int> ItemLength8 { get; set; }
        public Nullable<int> ItemAmount9 { get; set; }
        public Nullable<int> ItemLength9 { get; set; }
        public Nullable<int> ItemAmount10 { get; set; }
        public Nullable<int> ItemLength10 { get; set; }
        public Nullable<int> ItemAmount11 { get; set; }
        public Nullable<int> ItemLength11 { get; set; }
        public Nullable<int> ItemAmount12 { get; set; }
        public Nullable<int> ItemLength12 { get; set; }
        public Nullable<int> ItemAmount13 { get; set; }
        public Nullable<int> ItemLength13 { get; set; }
        public Nullable<int> ItemAmount14 { get; set; }
        public Nullable<int> ItemLength14 { get; set; }
        public Nullable<int> ItemAmount15 { get; set; }
        public Nullable<int> ItemLength15 { get; set; }
        public string RecipeNumber { get; set; }
        public string PipeBatch { get; set; }
        public string PipeNumber { get; set; }
        public string PipeHeat { get; set; }
        public string PipeSteel { get; set; }
        public Nullable<int> PipeDiameter { get; set; }
        public Nullable<int> PipeThickness { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string State { get; set; }
    }
}
