//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasker
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTask
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public Nullable<int> Position { get; set; }
        public string Item { get; set; }
        public string ItemBatch { get; set; }
        public string ItemBeginSerial { get; set; }
        public Nullable<int> ItemTargetAmount { get; set; }
        public Nullable<int> ItemLength { get; set; }
        public string RecipeNumber { get; set; }
        public string PipeBatch { get; set; }
        public string PipeNumber { get; set; }
        public string PipeHeat { get; set; }
        public string PipeSteel { get; set; }
        public Nullable<int> PipeDiameter { get; set; }
        public Nullable<int> PipeThickness { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
