//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasker
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskResult
    {
        public int Id { get; set; }
        public Nullable<int> ProductionTask_Id { get; set; }
        public Nullable<int> ItemAmount { get; set; }
        public Nullable<bool> Interrupt { get; set; }
        public string RecipeNumber { get; set; }
        public string MachineBrand { get; set; }
        public Nullable<int> BandType { get; set; }
        public Nullable<float> BandSpeed { get; set; }
        public Nullable<float> SawDownSpeed { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
    }
}
